spring.application.name=Room-Rental-Service
# Database Configuration

spring.datasource.url=${dbUrl:jdbc:mysql://mysql-team-vk1.alwaysdata.net:3306/team-vk1_rental_room_db}
spring.datasource.username=${dbUserName:team-vk1_nikhil}
spring.datasource.password=${DbPassword:nikhil@12}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# JWT Configuration
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expirationMs=604800000
app.jwt.refreshExpirationMs=2592000000



# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nikhilpatel03022004@gmail.com
spring.mail.password=wzxl qbgn smxi mund
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# Google OAuth Configuration
google.client.id=1059255546776-6fiqjph21l9v7e7ab0uui6k0u1ocudo4.apps.googleusercontent.com
# Razorpay Configuration
razorpay.key_id=rzp_test_tIxTQaPGx1Atly
razorpay.key_secret=KVs3IKXezJmcGAt4vyU866bh
# Cloudinary Configuration
cloudinary.cloud_name=dmqa8d6yq
cloudinary.api_key=859326834471994
cloudinary.api_secret=z40TdCn7fvSlZeCZ26kxoLNWVcQ
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB
#spring.servlet.multipart.max-file-count=50
server.tomcat.max-swallow-size=-1
server.tomcat.max-http-form-post-size=100MB
# Enable stacktrace in response for debugging
spring.web.error.include-stacktrace=always
spring.web.error.include-message=always


server.port=${PORT:8080}