name: Auto Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 13.200.125.193
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22
          timeout: 30s
          command_timeout: 5m
          script_stop: true
          script: |
            echo "Connected to EC2"
            bash /home/ubuntu/deploy/deploy.sh
            echo "Deployment finished"